### ISSUE TITLE
Adapt ContactDetailsFragment UI for launching Maps features

### ISSUE THREAD

**Issue by schuetzcarl** [Factotum-sdp/Factotum#105]
Need to be done before #86 

Possibility to launch Maps features like : 
- Run a route between the current phone position and the Coordinates stored in the corresponding Contact object.
- Display on the map the Coordinates stored in the corresponding Contact object.

**Comment by schuetzcarl** [comment]
@TimVW7, @DanielTavaresA  This one is closed I think, I let the person who implemented link it to the PR and close it.

**Comment by DanielTavaresA** [comment]
Still needs to wait on #174 to be fully closed
