### ISSUE TITLE
Implement MainActivity UI

### ISSUE THREAD

**Issue by yanvow** [Factotum-sdp/Factotum#8]
- Display the queued list with some destination records
- Left side menu with button to access to the contact diary activity
- Display of a button to access the map activity
- Display of a button to triggers the picture proof send to the customer
- Display the current user profile used

Guiding paper example :

![Image](https://user-images.githubusercontent.com/60784977/222761880-bdd39764-3294-4e82-b17c-44779ca39300.jpg)
![Image](https://user-images.githubusercontent.com/60784977/222761882-14411c9c-0b05-452b-be75-2fefcc8903ae.jpg)

**Comment by schuetzcarl** [comment]
Resolved in #22
